In [2]:
import numpy as np

In [6]:
l = [1, 2, 3, 4, 5, "Tejas" , 10.5]
arr = np.array(l)
arr

array(['1', '2', '3', '4', '5', 'Tejas', '10.5'], dtype='<U32')

**Array Generating Functions**

In [7]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])