# **NUMPY**

- Basic Array Operations

In [52]:
import numpy as np

In [53]:
list= [1, 2, 3, 4, 5, 6.5]
array= np.array(list)
array

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [54]:
arr= [1,2,3,4.5,"Rahul"]
arr

[1, 2, 3, 4.5, 'Rahul']

In [55]:
np.array(arr)

array(['1', '2', '3', '4.5', 'Rahul'], dtype='<U32')

- Matrices (2D)

In [56]:
arr1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
   
]

arr1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [57]:
arr1 = [
  [  [1, 2, 3],
    [4, 5, 6]
 ],
  [  [10, 11, 12],
    [13, 14, 15],
 ],
]
arr1

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]

- Array generations functions

In [58]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [60]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [61]:
arr=np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
arr=np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

- **Random Generation Functions**

In [63]:
np.random.rand(4)

array([0.43871848, 0.52494778, 0.59133073, 0.60954595])

In [64]:
np.random.rand(3,4)


array([[0.53524162, 0.71332598, 0.02781151, 0.22436855],
       [0.26043789, 0.22797686, 0.03774268, 0.74055533],
       [0.06455813, 0.767525  , 0.4106564 , 0.47799015]])

In [65]:
np.random.randn(2,4)

array([[-0.89781196,  1.08211794, -0.14361721,  0.80887082],
       [ 0.79897352, -2.18958225, -0.03985837,  0.31986596]])

In [66]:
np.random.randint(10,50)

48

In [67]:
np.random.randint(1,30,10)

array([ 3,  8, 11,  5,  7,  5, 11, 19, 22, 15], dtype=int32)

- **Array Attributes**

In [68]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr.shape

(3, 3)

In [70]:
arr.size

9

In [71]:
arr.dtype

dtype('int64')

- **Array Method**

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr.min()

np.int64(1)

In [74]:
arr.max()

np.int64(9)

In [75]:
arr.sum()

np.int64(45)

In [76]:
np.sum(arr,axis=1)


array([ 6, 15, 24])

In [77]:
np.sum(arr,axis=0)

array([12, 15, 18])

- **Reshaping and Resizing**

In [78]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [79]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

#Array indexing and slicing of vectors

In [80]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [81]:
arr[6]

np.int64(17)

In [82]:
arr[0:6]

array([11, 12, 13, 14, 15, 16])

In [83]:
arr[0:5:2]

array([11, 13, 15])

- **Numpy Indexing and Slicing of Matrix**

In [84]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [85]:
arr[3]

array([19, 20, 21, 22, 23, 24])

In [86]:
arr[:,4]

array([ 5, 11, 17, 23, 29, 35])

In [87]:
arr[1,1]

np.int64(8)