# **NUMPY**

- **Basic Array Operations**

In [172]:
import numpy as np

In [173]:
list= [1, 2, 3, 4, 5, 6.5]
array= np.array(list)
array

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [174]:
arr= [1,2,3,4.5,"Rahul"]
arr

[1, 2, 3, 4.5, 'Rahul']

In [175]:
np.array(arr)

array(['1', '2', '3', '4.5', 'Rahul'], dtype='<U32')

- **Matrices (2D)**

In [176]:
arr1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
   
]

arr1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [177]:
arr1 = [
  [  [1, 2, 3],
    [4, 5, 6]
 ],
  [  [10, 11, 12],
    [13, 14, 15],
 ],
]
arr1

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]

- **Array generation functions**

In [178]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [179]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [180]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [181]:
arr=np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [182]:
arr=np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

- **Random Generation Functions**

In [183]:
np.random.rand(4)

array([0.06531812, 0.83179573, 0.41273969, 0.44461931])

In [184]:
np.random.rand(3,4)


array([[0.89761499, 0.41741022, 0.01702777, 0.35344567],
       [0.14766204, 0.09688176, 0.01305735, 0.13993068],
       [0.9096962 , 0.5636347 , 0.96936765, 0.98054143]])

In [185]:
np.random.randn(2,4)

array([[-2.72689715, -1.70689792,  1.78537195,  0.14002523],
       [ 0.77138413,  0.97322721, -0.53210082,  0.13438291]])

In [186]:
np.random.randint(10,50)

31

In [187]:
np.random.randint(1,30,10)

array([13, 28,  2, 17,  8, 26, 15, 13, 11, 24], dtype=int32)

- **Array Attributes**

In [188]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
arr.shape

(3, 3)

In [190]:
arr.size

9

In [191]:
arr.dtype

dtype('int64')

- **Array Method**

In [192]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
arr.min()

np.int64(1)

In [194]:
arr.max()

np.int64(9)

In [195]:
arr.sum()

np.int64(45)

In [196]:
np.sum(arr,axis=1)


array([ 6, 15, 24])

In [197]:
np.sum(arr,axis=0)

array([12, 15, 18])

- **Reshaping and Resizing**

In [198]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [199]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

 - #Array indexing and slicing of vectors

In [200]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [201]:
arr[6]

np.int64(17)

In [202]:
arr[0:6]

array([11, 12, 13, 14, 15, 16])

In [203]:
arr[0:5:2]

array([11, 13, 15])

- **Numpy Indexing and Slicing of Matrix**

In [204]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [205]:
arr[3]

array([19, 20, 21, 22, 23, 24])

In [206]:
arr[:,4]

array([ 5, 11, 17, 23, 29, 35])

In [207]:
arr[1,1]

np.int64(8)

- **Boolean Indexing**

In [208]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [209]:
boolean_index= arr%2 ==0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [210]:
arr=arr[boolean_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**Numpy - Array Operations**

In [211]:
import numpy as np

- **Arithmetic Operations**


In [212]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [213]:
a3=a1+a2
a3

array([ 7,  9, 11, 13, 15])

In [214]:
a3=a1**a2
a3

array([      1,     128,    6561,  262144, 9765625])

- **Broadcasting**

In [215]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [216]:
arr+10

array([20, 30, 40, 50, 60])

- **Deep and Shallow Copy**

In [217]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [218]:
slice=arr[ :5]
slice=slice*10
slice

array([100, 200, 300, 400, 500])

In [219]:
a  #Deep Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [220]:
b=a.copy()   #Shallow Copy
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [221]:
b[2]=2000
b

array([   1,    2, 2000,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

- **Matrix Operations**

In [222]:
A=np.array(([1,2],[4,5]))
B=np.array(([7,8],[9,10]))

In [223]:
A

array([[1, 2],
       [4, 5]])

In [224]:
B

array([[ 7,  8],
       [ 9, 10]])

In [225]:
A+B

array([[ 8, 10],
       [13, 15]])

In [226]:
A*B

array([[ 7, 16],
       [36, 50]])

In [227]:
A@B

array([[25, 28],
       [73, 82]])

- *Transpose of Matrix*

In [228]:
A.T

array([[1, 4],
       [2, 5]])

In [229]:
B.T

array([[ 7,  9],
       [ 8, 10]])

- **Advance Array Manipulations**

In [230]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [231]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [232]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

- **Spliting Array**

In [234]:
s=np.arange(16).reshape(4,4)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [235]:
np.vsplit(s,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [236]:
np.hsplit(s,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

-    **THIS IS THE END**