# Numpy

- Basic Array Operations

In [1]:
import numpy as np

In [19]:
list= [1, 2, 3, 4, 5, 6.5]
array= np.array(list)
array

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [34]:
arr= [1,2,3,4.5,"Rahul"]
arr

[1, 2, 3, 4.5, 'Rahul']

In [38]:
np.array(arr)

array(['1', '2', '3', '4.5', 'Rahul'], dtype='<U32')

- Matrices (2D)

In [ ]:
arr1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
   
]

arr1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
arr1 = [
  [  [1, 2, 3],
    [4, 5, 6]
 ],
  [  [10, 11, 12],
    [13, 14, 15],
 ],
]
arr1

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]

- Array generations functions

In [26]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [29]:
arr=np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr=np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

- Random Generation Functions

In [39]:
np.random.rand(4)

array([0.22454584, 0.15633274, 0.92295404, 0.45753924])

In [42]:
np.random.rand(3,4)


array([[0.79009838, 0.87267359, 0.73688501, 0.42597469],
       [0.38269877, 0.36565497, 0.20726427, 0.7573765 ],
       [0.42963164, 0.64153223, 0.77078486, 0.9001305 ]])

In [46]:
np.random.randn(2,4)

array([[-2.92970267, -1.21079276,  0.91438936,  0.7481162 ],
       [ 0.13037375, -0.84809013, -1.48078125,  0.18112781]])

In [47]:
np.random.randint(10,50)

30

In [48]:
np.random.randint(1,30,10)

array([26, 12,  6, 15, 19,  7, 27, 18, 16, 22], dtype=int32)

- Array Attributes

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.shape

(3, 3)

In [51]:
arr.size

9

In [52]:
arr.dtype

dtype('int64')

- Array Method

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.min()

np.int64(1)

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.sum()

np.int64(45)

In [58]:
np.sum(arr,axis=1)

array([ 6, 15, 24])