# **NUMPY**

- **Basic Array Operations**

In [1]:
import numpy as np

In [2]:
list= [1, 2, 3, 4, 5, 6.5]
array= np.array(list)
array

array([1. , 2. , 3. , 4. , 5. , 6.5])

In [3]:
arr= [1,2,3,4.5,"Rahul"]
arr

[1, 2, 3, 4.5, 'Rahul']

In [4]:
np.array(arr)

array(['1', '2', '3', '4.5', 'Rahul'], dtype='<U32')

- Matrices (2D)

In [5]:
arr1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
   
]

arr1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr1 = [
  [  [1, 2, 3],
    [4, 5, 6]
 ],
  [  [10, 11, 12],
    [13, 14, 15],
 ],
]
arr1

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]

- Array generations functions

In [7]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [9]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [10]:
arr=np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr=np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

- **Random Generation Functions**

In [12]:
np.random.rand(4)

array([0.29669568, 0.62715399, 0.33070528, 0.87680591])

In [13]:
np.random.rand(3,4)


array([[0.90959577, 0.46130655, 0.27116189, 0.78246951],
       [0.89636226, 0.71361409, 0.11351065, 0.02645309],
       [0.14223964, 0.90534191, 0.86673008, 0.12899047]])

In [14]:
np.random.randn(2,4)

array([[-1.8182155 ,  0.16932106, -0.19698433, -1.04358608],
       [-0.64753963,  0.42339412,  0.73419273,  0.37665895]])

In [15]:
np.random.randint(10,50)

19

In [16]:
np.random.randint(1,30,10)

array([11, 23, 20,  5,  1,  2, 25,  9, 17, 21], dtype=int32)

- **Array Attributes**

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

- **Array Method**

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr,axis=1)


array([ 6, 15, 24])

In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

- **Reshaping and Resizing**

In [27]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
arr=arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

#Array indexing and slicing of vectors

In [29]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
arr[6]

np.int64(17)

In [31]:
arr[0:6]

array([11, 12, 13, 14, 15, 16])

In [32]:
arr[0:5:2]

array([11, 13, 15])

- **Numpy Indexing and Slicing of Matrix**

In [33]:
arr=np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [34]:
arr[3]

array([19, 20, 21, 22, 23, 24])

In [35]:
arr[:,4]

array([ 5, 11, 17, 23, 29, 35])

In [36]:
arr[1,1]

np.int64(8)